server.port=4001
spring.application.name=SpringBootApiRest
spring.datasource.url=jdbc:postgresql://localhost:5432/DBGestion
spring.datasource.username=postgres
spring.datasource.password=19962696Ee
spring.jpa.hibernate.ddl-auto=update